module Add = { @module("@mui/icons-material/Add") @react.component external make: () => React.element = "default" }
module ArrowDownward = { @module("@mui/icons-material/ArrowDownward") @react.component external make: () => React.element = "default" }
module ArrowUpward = { @module("@mui/icons-material/ArrowUpward") @react.component external make: () => React.element = "default" }
module CancelOutlined = { @module("@mui/icons-material/CancelOutlined") @react.component external make: () => React.element = "default" }
module ControlPointDuplicate = { @module("@mui/icons-material/ControlPointDuplicate") @react.component external make: () => React.element = "default" }
module DeleteForever = { @module("@mui/icons-material/DeleteForever") @react.component external make: () => React.element = "default" }
module Delete = { @module("@mui/icons-material/Delete") @react.component external make: () => React.element = "default" }
module ExpandMore = { @module("@mui/icons-material/ExpandMore") @react.component external make: () => React.element = "default" }
module FilterNone = { @module("@mui/icons-material/FilterNone") @react.component external make: () => React.element = "default" }
module Hub = { @module("@mui/icons-material/Hub") @react.component external make: () => React.element = "default" }
module IosShare = { @module("@mui/icons-material/IosShare") @react.component external make: () => React.element = "default" }
module Save = { @module("@mui/icons-material/Save") @react.component external make: () => React.element = "default" }
module Search = { @module("@mui/icons-material/Search") @react.component external make: () => React.element = "default" }
module Settings = { @module("@mui/icons-material/Settings") @react.component external make: () => React.element = "default" }
module Sync = { @module("@mui/icons-material/Sync") @react.component external make: () => React.element = "default" }
module TextRotationNone = { @module("@mui/icons-material/TextRotationNone") @react.component external make: () => React.element = "default" }